/**
* Api Documentation
* Api Documentation
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.github.eaxdev.dto.response


import com.fasterxml.jackson.annotation.JsonProperty
/**
 * 
 * @param address 
 * @param dayOfWeek 
 * @param hourOfDay 
 * @param id 
 * @param lat 
 * @param lon 
 * @param predicting 
 * @param title 
 */

data class BranchDtoWithPredicting (
    @JsonProperty("address")
    val address: kotlin.String? = null,
    @JsonProperty("dayOfWeek")
    val dayOfWeek: kotlin.Int? = null,
    @JsonProperty("hourOfDay")
    val hourOfDay: kotlin.Int? = null,
    @JsonProperty("id")
    val id: kotlin.Long? = null,
    @JsonProperty("lat")
    val lat: kotlin.Double? = null,
    @JsonProperty("lon")
    val lon: kotlin.Double? = null,
    @JsonProperty("predicting")
    val predicting: kotlin.Long? = null,
    @JsonProperty("title")
    val title: kotlin.String? = null
)

