/**
* Api Documentation
* Api Documentation
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.github.eaxdev.dto.response


import com.fasterxml.jackson.annotation.JsonProperty
/**
 * 
 * @param status 
 */

data class ErrorResponse (
    @JsonProperty("status")
    val status: kotlin.String? = null
)

