/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.github.eaxdev.dto.response


import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 * @param city
 * @param deviceId
 * @param latitude
 * @param location
 * @param longitude
 * @param payments
 */

data class AtmResponse(
    @JsonProperty("city")
    val city: kotlin.String? = null,
    @JsonProperty("deviceId")
    val deviceId: kotlin.Int? = null,
    @JsonProperty("latitude")
    val latitude: kotlin.String? = null,
    @JsonProperty("location")
    val location: kotlin.String? = null,
    @JsonProperty("longitude")
    val longitude: kotlin.String? = null,
    @JsonProperty("payments")
    val payments: kotlin.Boolean? = null
)

